var STONES = [
  { id:"pandola", name:"潘多拉", nameEn:"Pandora", origin:"巴西", type:"石英岩", description:"金丝缠绕、石中裹玉，白米灰黑金交织", sortOrder:1,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[{label:"客厅实景",src:"images/placeholder/scene.jpg"}] }},
  { id:"yudubai", name:"鱼肚白", nameEn:"Calacatta", origin:"意大利", type:"大理石", description:"白色天花板级，温润如玉，产量仅占矿山5%", sortOrder:2,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"},{type:"背景墙",src:"images/placeholder/wall.jpg"}], scenes:[{label:"客厅实景",src:"images/placeholder/scene.jpg"}] }},
  { id:"xuehuabai", name:"雪花白", nameEn:"Statuario", origin:"意大利", type:"大理石", description:"纯净白色，自古罗马时期即为权贵象征", sortOrder:3,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[{label:"客厅实景",src:"images/placeholder/scene.jpg"}] }},
  { id:"baogeli", name:"宝格丽", nameEn:"Bvlgari", origin:"意大利", type:"大理石", description:"白底黑紫色花纹，简约优雅", sortOrder:4,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[] }},
  { id:"fendibai", name:"芬迪白", nameEn:"Fendi White", origin:"意大利", type:"大理石", description:"洁白底色通透，灰色与白色晶体飘逸", sortOrder:5,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[{label:"客厅实景",src:"images/placeholder/scene.jpg"}] }},
  { id:"xiongmaobai", name:"熊猫白", nameEn:"Panda White", origin:"中国", type:"大理石", description:"黑白交错水墨感，国产奢石佼佼者", sortOrder:6,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"},{type:"背景墙",src:"images/placeholder/wall.jpg"}], scenes:[{label:"客厅实景",src:"images/placeholder/scene.jpg"}] }},
  { id:"xinghe", name:"星河传说", nameEn:"Galaxy Legend", origin:"巴西", type:"大理石", description:"黑底金黄色纹理，如银河般包罗万象", sortOrder:7,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[{label:"客厅实景",src:"images/placeholder/scene.jpg"}] }},
  { id:"jingtailan", name:"景泰蓝", nameEn:"Cloisonne", origin:"巴西", type:"大理石", description:"富含青金石，深邃秘境蓝，蓝色奢石至尊", sortOrder:8,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"},{type:"背景墙",src:"images/placeholder/wall.jpg"}], scenes:[] }},
  { id:"lengfeicui", name:"冷翡翠", nameEn:"Cold Jade", origin:"巴西", type:"大理石", description:"温润白玉底黑绿色花纹，如翡翠般灵动", sortOrder:9,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[{label:"客厅实景",src:"images/placeholder/scene.jpg"}] }},
  { id:"napolunhei", name:"拿破仑黑", nameEn:"Napoleon Black", origin:"法国", type:"大理石", description:"黑白高对比度，极具现代冲击感", sortOrder:10,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"},{type:"茶几",src:"images/placeholder/table.jpg"}], scenes:[{label:"客厅实景",src:"images/placeholder/scene.jpg"}] }},
  { id:"zishanshui", name:"紫山水", nameEn:"Purple Landscape", origin:"中国", type:"大理石", description:"紫红色为主，如墨画山川，东方古典气息", sortOrder:11,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[] }},
  { id:"xiangxuemei", name:"香雪梅", nameEn:"Fragrant Snow Plum", origin:"巴西", type:"大理石", description:"雪中淡紫梅枝纹理，纤长优雅", sortOrder:12,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[] }},
  { id:"shuiyunsha", name:"水云纱", nameEn:"Water Cloud", origin:"巴西", type:"大理石", description:"如行云流水，波浪状线条层层推进", sortOrder:13,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[{label:"客厅实景",src:"images/placeholder/scene.jpg"}] }},
  { id:"weinisizong", name:"威尼斯棕", nameEn:"Venetian Brown", origin:"意大利", type:"大理石", description:"棕色油画质感，海浪般层次", sortOrder:14,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[] }},
  { id:"yinhu", name:"银狐", nameEn:"Silver Fox", origin:"巴西", type:"大理石", description:"银灰底白色纹理，如狐尾飘逸", sortOrder:15,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[{label:"客厅实景",src:"images/placeholder/scene.jpg"}] }},
  { id:"lanfeicui", name:"蓝翡翠", nameEn:"Blue Jade", origin:"巴西", type:"大理石", description:"尊蓝基底黑色云母蓝色月光宝石，宛若宇宙星河", sortOrder:16,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"},{type:"背景墙",src:"images/placeholder/wall.jpg"}], scenes:[{label:"客厅实景",src:"images/placeholder/scene.jpg"}] }},
  { id:"yamasunlv", name:"亚马逊绿", nameEn:"Amazon Green", origin:"巴西", type:"石英岩", description:"宝石级别，湖水蓝绿色，含天河石成分", sortOrder:17,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[{label:"客厅实景",src:"images/placeholder/scene.jpg"}] }},
  { id:"hudiemeng", name:"蝴蝶梦", nameEn:"Tropical Dream", origin:"巴西", type:"石英岩", description:"10亿年以上形成，金白色纹路璀璨夺目", sortOrder:18,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[] }},
  { id:"gelanyuntian", name:"格兰云天", nameEn:"Blue Sky", origin:"巴西", type:"石英岩", description:"蓝白色调，自带天空元素，地中海风格", sortOrder:19,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[] }},
  { id:"boliweiyalan", name:"玻利维亚蓝", nameEn:"Bolivian Blue", origin:"玻利维亚", type:"石英岩", description:"深蓝透浅蓝，乳白纹路如微霜雾雨", sortOrder:20,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"},{type:"背景墙",src:"images/placeholder/wall.jpg"}], scenes:[{label:"客厅实景",src:"images/placeholder/scene.jpg"}] }},
  { id:"canghaiyizhu", name:"沧海遗珠", nameEn:"Ocean Pearl", origin:"巴西", type:"石英岩", description:"绚丽色彩，晶莹质地", sortOrder:21,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[] }},
  { id:"bingshangjinghua", name:"冰上晶花", nameEn:"Ice Crystal", origin:"巴西", type:"石英岩", description:"水晶晶体成簇如花绽放", sortOrder:22,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[] }},
  { id:"puladalv", name:"普拉达绿", nameEn:"Prada Green", origin:"意大利", type:"石英岩", description:"复古绿，如翡翠湖激起浪花", sortOrder:23,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[{label:"客厅实景",src:"images/placeholder/scene.jpg"}] }},
  { id:"luofuhuanying", name:"罗浮幻影", nameEn:"Louvre Phantom", origin:"意大利", type:"石英岩", description:"复刻意大利高端白石，曾用于巴黎罗浮宫", sortOrder:24,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"},{type:"背景墙",src:"images/placeholder/wall.jpg"}], scenes:[{label:"客厅实景",src:"images/placeholder/scene.jpg"}] }},
  { id:"lanmanao", name:"蓝玛瑙", nameEn:"Blue Agate", origin:"巴西", type:"玛瑙", description:"深蓝色，雪花晶体碎片带来三维立体感，可透光", sortOrder:25,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[] }},
  { id:"yindumanao", name:"印度玛瑙", nameEn:"Indian Agate", origin:"印度", type:"玛瑙", description:"红灰蓝绿交融，独特异国风情", sortOrder:26,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[] }},
  { id:"wulagui", name:"乌拉圭玛瑙", nameEn:"Uruguay Agate", origin:"乌拉圭", type:"玛瑙", description:"多色交融，多用于台面装饰", sortOrder:27,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[] }},
  { id:"baxiheijinsha", name:"巴西黑金沙", nameEn:"Black Galaxy", origin:"巴西", type:"玛瑙", description:"黑色金色晶体，如银河星带梦幻流光", sortOrder:28,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[{label:"客厅实景",src:"images/placeholder/scene.jpg"}] }},
  { id:"baiyu", name:"白玉", nameEn:"White Jade", origin:"中国", type:"玉石", description:"白或黄，若云霞漫天，材质细腻透光", sortOrder:29,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[] }},
  { id:"caiyu", name:"彩玉", nameEn:"Color Jade", origin:"中国", type:"玉石", description:"色彩绚烂多变", sortOrder:30,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[] }},
  { id:"ziyingyu", name:"紫莹玉", nameEn:"Purple Jade", origin:"巴西", type:"玉石", description:"紫色调，通透温润", sortOrder:31,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[] }},
  { id:"hongdongshi", name:"红洞石", nameEn:"Red Travertine", origin:"意大利", type:"玉石", description:"浓郁色差，天然孔洞带历史厚重感", sortOrder:32,
    images:{ slab:"images/placeholder/slab.jpg", products:[{type:"餐桌",src:"images/placeholder/table.jpg"}], scenes:[{label:"客厅实景",src:"images/placeholder/scene.jpg"}] }}
];
