/**
 * 扫描「图库三」下每个品类文件夹：
 * - 图片：jpg / jpeg / png / webp / gif / bmp
 * - 规格：该文件夹内按文件名排序后的第一个 .txt（若多个 txt，只认第一个）
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const GALLERY_DIR = path.join(ROOT, '图库三');
const OUT_FILE = path.join(ROOT, 'js', 'gallery-data.js');
const CURATED_JSON = path.join(__dirname, 'gallery-curated-folders.json');

const IMAGE_EXT = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif', '.bmp']);

function isImageFile(name) {
  return IMAGE_EXT.has(path.extname(name).toLowerCase());
}

function parseTxtSpecs(content) {
  const lines = String(content).split(/\r?\n/);
  const pairs = [];
  let pendingCode = null;
  const codeRe = /^编号\s*[：:]\s*(.+)$/;
  const specRe = /^规格\s*[：:]\s*(.+)$/;

  for (const line of lines) {
    const t = line.trim();
    const cm = t.match(codeRe);
    const sm = t.match(specRe);
    if (cm) pendingCode = cm[1].trim();
    if (sm && pendingCode !== null) {
      const rawSpec = sm[1].trim();
      pairs.push({
        code: pendingCode,
        rawSpec,
        specDisplay: formatSpecDisplay(rawSpec),
      });
      pendingCode = null;
    }
  }
  return pairs;
}

function formatSpecDisplay(raw) {
  if (!raw) return '';
  let s = raw.replace(/\*\*/g, '*').replace(/\s+/g, ' ').trim();
  s = s.replace(/[×xX]/g, '*');
  const parts = s.split('*').map((p) => p.trim()).filter(Boolean);
  const nums = parts.map((p) => p.replace(/[^\d.]/g, '')).filter(Boolean);
  if (nums.length >= 2) {
    return nums.slice(0, 3).join(' × ') + ' mm';
  }
  return s;
}

function isTrivialSpec(row) {
  return row.code === '1' && (row.rawSpec === '1' || row.specDisplay === '1');
}

function scanCategory(folderPath, folderName) {
  const files = fs
    .readdirSync(folderPath, { withFileTypes: true })
    .filter((d) => d.isFile())
    .map((d) => d.name);

  const txts = files
    .filter((f) => f.toLowerCase().endsWith('.txt'))
    .sort((a, b) => a.localeCompare(b, 'zh-CN'));

  const firstTxt = txts[0] || null;
  let specs = [];
  if (firstTxt) {
    const textPath = path.join(folderPath, firstTxt);
    const content = fs.readFileSync(textPath, 'utf8');
    specs = parseTxtSpecs(content).filter((r) => !isTrivialSpec(r));
  }

  const images = files
    .filter((f) => isImageFile(f))
    .sort((a, b) => a.localeCompare(b, 'zh-CN', { numeric: true }));

  const relImages = images.map((f) => path.join('图库三', folderName, f).split(path.sep).join('/'));

  return {
    folder: folderName,
    specs,
    images: relImages,
  };
}

function pickHomeHero(categories) {
  for (const c of categories) {
    if (c.images && c.images.length > 0) return c.images[0];
  }
  return null;
}

function loadCuratedFolderOrder() {
  if (!fs.existsSync(CURATED_JSON)) return [];
  try {
    const raw = fs.readFileSync(CURATED_JSON, 'utf8');
    const data = JSON.parse(raw);
    if (!Array.isArray(data)) return [];
    return data.map((x) => String(x).trim()).filter(Boolean);
  } catch (e) {
    console.warn('读取 scripts/gallery-curated-folders.json 失败:', e.message);
    return [];
  }
}

function resolveCuratedFolders(requested, categories) {
  const existing = new Set(categories.map((c) => c.folder));
  const out = [];
  for (const name of requested) {
    if (existing.has(name)) out.push(name);
    else console.warn('精选列表中的品类不在图库三中，已跳过:', name);
  }
  return out;
}

function writeOutput(categories, hero, curatedFolders) {
  const banner =
    '/* Auto-generated by scripts/build-gallery.mjs. Do not edit by hand. Re-run: npm run build:gallery */\n';
  const body =
    'var GALLERY_CATEGORIES = ' +
    JSON.stringify(categories, null, 2) +
    ';\n' +
    'var GALLERY_HOME_HERO = ' +
    (hero === null ? 'null' : JSON.stringify(hero)) +
    ';\n' +
    'var GALLERY_CURATED_FOLDERS = ' +
    JSON.stringify(curatedFolders, null, 2) +
    ';\n';
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, banner + body, 'utf8');
}

function main() {
  if (!fs.existsSync(GALLERY_DIR)) {
    console.warn('未找到 图库三 目录，已写入空的 GALLERY_CATEGORIES。');
    writeOutput([], null, []);
    return;
  }

  const dirNames = fs
    .readdirSync(GALLERY_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .filter((name) => !name.startsWith('.'))
    .sort((a, b) => a.localeCompare(b, 'zh-CN'));

  const categories = dirNames.map((name) => scanCategory(path.join(GALLERY_DIR, name), name));
  const hero = pickHomeHero(categories);
  const curatedFolders = resolveCuratedFolders(loadCuratedFolderOrder(), categories);
  if (curatedFolders.length) {
    console.log('精选品类（图库三已匹配）', curatedFolders.length, '个。');
  } else {
    console.warn('未配置有效精选列表（检查 scripts/gallery-curated-folders.json）。');
  }
  writeOutput(categories, hero, curatedFolders);
  console.log('已写入 js/gallery-data.js，共', categories.length, '个品类。');
}

main();
